# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9021
    hooks:
    -   id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
        exclude: >
          (?x)^(
          R/RcppExports.R|
          src/RcppExports.cpp|
          )$
    # -   id: roxygenize
    #     # roxygen requires loading pkg -> add dependencies from DESCRIPTION
    #     additional_dependencies:
    #     -    Matrix
    #     -    Rcpp
    -   id: use-tidy-description
    -   id: spell-check
        exclude: >
          (?x)^(
          .*\.[rR]|
          .*\.feather|
          .*\.jpeg|
          .*\.pdf|
          .*\.png|
          .*\.py|
          .*\.RData|
          .*\.rds|
          .*\.Rds|
          .*\.Rproj|
          .*\.sh|
          (.*/|)\<.gitignore|
          (.*/|)\.gitlab-ci\.yml|
          (.*/|)\.lintr|
          (.*/|)\.pre-commit-.*|
          (.*/|)\.Rbuildignore|
          (.*/|)\.Renviron|
          (.*/|)\.Rprofile|
          (.*/|)\.travis\.yml|
          (.*/|)appveyor\.yml|
          (.*/|)NAMESPACE|
          (.*/|)renv/settings\.dcf|
          (.*/|)renv\.lock|
          (.*/|)WORDLIST|
          \.github/workflows/.*|
          data/.*|
          src/RcppExports\.cpp|
          R/RcppExports\.R|
          )$
    -   id: lintr
        args: [--warn_only]
        verbose: false
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: no-print-statement
    -   id: no-debug-statement
    -   id: deps-in-desc
        exclude: >
          (?x)^(
          inst/check_speed.R|
          )$
    -   id: pkgdown
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v22.1.2
  hooks:
    - id: clang-format
      args: ["--style=Google"]
      exclude: ./src/RcppExports.cpp
- repo: https://github.com/cpplint/cpplint
  rev: 2.0.2
  hooks:
    - id: cpplint
      args:
        - --exclude=src/RcppExports.cpp
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=200']
    -   id: file-contents-sorter
        files: '^\.Rbuildignore$'
    # -   id: end-of-file-fixer
    #     exclude: '\.Rd,R/RcppExports.R'
-   repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.6.1
    hooks:
    # Only required when https://pre-commit.ci is used for config validation
    -   id: check-pre-commit-ci-config
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData
        language: fail
        files: '\.(Rhistory|RData|)$'
        # `exclude: <regex>` to allow committing specific files

ci:
    autoupdate_schedule: monthly
    skip: [pkgdown]
