// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>& Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_SortPairs
Rcpp::List cpp_SortPairs(Rcpp::IntegerVector& c1, Rcpp::IntegerVector& c2,
                         unsigned int N1, unsigned int N2);
RcppExport SEXP _aricode_cpp_SortPairs(SEXP c1SEXP, SEXP c2SEXP, SEXP N1SEXP,
                                       SEXP N2SEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter<Rcpp::IntegerVector&>::type c1(c1SEXP);
  Rcpp::traits::input_parameter<Rcpp::IntegerVector&>::type c2(c2SEXP);
  Rcpp::traits::input_parameter<unsigned int>::type N1(N1SEXP);
  Rcpp::traits::input_parameter<unsigned int>::type N2(N2SEXP);
  rcpp_result_gen = Rcpp::wrap(cpp_SortPairs(c1, c2, N1, N2));
  return rcpp_result_gen;
  END_RCPP
}
// std_SortPairs
Rcpp::List std_SortPairs(Rcpp::IntegerVector c1_in, Rcpp::IntegerVector c2_in,
                         unsigned int N1, unsigned int N2);
RcppExport SEXP _aricode_std_SortPairs(SEXP c1_inSEXP, SEXP c2_inSEXP,
                                       SEXP N1SEXP, SEXP N2SEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter<Rcpp::IntegerVector>::type c1_in(c1_inSEXP);
  Rcpp::traits::input_parameter<Rcpp::IntegerVector>::type c2_in(c2_inSEXP);
  Rcpp::traits::input_parameter<unsigned int>::type N1(N1SEXP);
  Rcpp::traits::input_parameter<unsigned int>::type N2(N2SEXP);
  rcpp_result_gen = Rcpp::wrap(std_SortPairs(c1_in, c2_in, N1, N2));
  return rcpp_result_gen;
  END_RCPP
}
// expected_MI
double expected_MI(Rcpp::IntegerVector ni_, Rcpp::IntegerVector n_j);
RcppExport SEXP _aricode_expected_MI(SEXP ni_SEXP, SEXP n_jSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter<Rcpp::IntegerVector>::type ni_(ni_SEXP);
  Rcpp::traits::input_parameter<Rcpp::IntegerVector>::type n_j(n_jSEXP);
  rcpp_result_gen = Rcpp::wrap(expected_MI(ni_, n_j));
  return rcpp_result_gen;
  END_RCPP
}
// getRank
Rcpp::List getRank(Rcpp::IntegerVector classi);
RcppExport SEXP _aricode_getRank(SEXP classiSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter<Rcpp::IntegerVector>::type classi(classiSEXP);
  rcpp_result_gen = Rcpp::wrap(getRank(classi));
  return rcpp_result_gen;
  END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_aricode_cpp_SortPairs", (DL_FUNC)&_aricode_cpp_SortPairs, 4},
    {"_aricode_std_SortPairs", (DL_FUNC)&_aricode_std_SortPairs, 4},
    {"_aricode_expected_MI", (DL_FUNC)&_aricode_expected_MI, 2},
    {"_aricode_getRank", (DL_FUNC)&_aricode_getRank, 1},
    {NULL, NULL, 0}};

RcppExport void R_init_aricode(DllInfo* dll) {
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
