# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getRank <- function(classif) {
    .Call('_aricode_getRank', PACKAGE = 'aricode', classif)
}

std_SortPairs <- function(c1_in, c2_in, N1, N2) {
    .Call('_aricode_std_SortPairs', PACKAGE = 'aricode', c1_in, c2_in, N1, N2)
}

expected_MI <- function(ni_, n_j) {
    .Call('_aricode_expected_MI', PACKAGE = 'aricode', ni_, n_j)
}

