# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_rank <- function(classif) {
    .Call('_aricode_get_rank', PACKAGE = 'aricode', classif)
}

std_sort_pairs <- function(c1_in, c2_in, N1, N2) {
    .Call('_aricode_std_sort_pairs', PACKAGE = 'aricode', c1_in, c2_in, N1, N2)
}

expected_MI <- function(ni_r, nj_r) {
    .Call('_aricode_expected_MI', PACKAGE = 'aricode', ni_r, nj_r)
}

